import type { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  await knex("organismos").insert([
    {
      id: 1,
      codigo: "JNQEJ",
      nombre: "Juzgado de Ejecución Neuquén",
      caratula: "Juzgado de Ejecución Neuquén",
      ciudad: "Neuquén",
      fuero: "Ejecutivos",
    },
    {
      id: 2,
      codigo: "JNQCI",
      nombre: "Juzgado Civil Neuquén",
      caratula: "Juzgado Civil Neuquén",
      ciudad: "Neuquén",
      fuero: "Civil",
    },
    {
      id: 3,
      codigo: "JNQLA",
      nombre: "Juzgado Laboral Neuquén",
      caratula: "Juzgado Laboral Neuquén",
      ciudad: "Neuquén",
      fuero: "Laboral",
    },
    {
      id: 4,
      codigo: "JNQFA",
      nombre: "Juzgado de Familia Neuquén",
      caratula: "Juzgado de Familia Neuquén",
      ciudad: "Neuquén",
      fuero: "Familia",
    },
    {
      id: 5,
      codigo: "JZAEJ",
      nombre: "Juzgado de Ejecución Zapala",
      caratula: "Juzgado de Ejecución Zapala",
      ciudad: "Zapala",
      fuero: "Ejecutivos",
    },
    {
      id: 6,
      codigo: "JZACI",
      nombre: "Juzgado Civil Zapala",
      caratula: "Juzgado Civil Zapala",
      ciudad: "Zapala",
      fuero: "Civil",
    },
    {
      id: 7,
      codigo: "JZALA",
      nombre: "Juzgado Laboral Zapala",
      caratula: "Juzgado Laboral Zapala",
      ciudad: "Zapala",
      fuero: "Laboral",
    },
    {
      id: 8,
      codigo: "JZAFA",
      nombre: "Juzgado de Familia Zapala",
      caratula: "Juzgado de Familia Zapala",
      ciudad: "Zapala",
      fuero: "Familia",
    },
    {
      id: 9,
      codigo: "JJUEJ",
      nombre: "Juzgado de Ejecución Junín de los Andes",
      caratula: "Juzgado de Ejecución Junín de los Andes",
      ciudad: "Junín de los Andes",
      fuero: "Ejecutivos",
    },
    {
      id: 10,
      codigo: "JJUCI",
      nombre: "Juzgado Civil Junín de los Andes",
      caratula: "Juzgado Civil Junín de los Andes",
      ciudad: "Junín de los Andes",
      fuero: "Civil",
    },
    {
      id: 11,
      codigo: "JJULA",
      nombre: "Juzgado Laboral Junín de los Andes",
      caratula: "Juzgado Laboral Junín de los Andes",
      ciudad: "Junín de los Andes",
      fuero: "Laboral",
    },
    {
      id: 12,
      codigo: "JJUFA",
      nombre: "Juzgado de Familia Junín de los Andes",
      caratula: "Juzgado de Familia Junín de los Andes",
      ciudad: "Junín de los Andes",
      fuero: "Familia",
    },
  ]);
}
