import type { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  await knex("expedientes").insert([
    {
      id: 1,
      codigo_organismo: "JNQFA",
      tipo: "EXP",
      numero: 101,
      anno: 2024,
      caratula: "García c/ López s/ Alimentos",
      ciudad: "Neuquén",
    },
    {
      id: 2,
      codigo_organismo: "JNQCI",
      tipo: "LEG",
      numero: 45,
      anno: 2023,
      caratula: "Sucesión de Fernández",
      ciudad: "Neuquén",
    },
    {
      id: 3,
      codigo_organismo: "JZACI",
      tipo: "EXP",
      numero: 78,
      anno: 2024,
      caratula: "Rodríguez c/ Martínez s/ Daños y Perjuicios",
      ciudad: "Zapala",
    },
    {
      id: 4,
      codigo_organismo: "JJUEJ",
      tipo: "EXP",
      numero: 12,
      anno: 2025,
      caratula: "Banco Patagonia c/ Sánchez s/ Ejecución de Sentencia",
      ciudad: "Junín de los Andes",
    },
    {
      id: 5,
      codigo_organismo: "JNQLA",
      tipo: "EXP",
      numero: 200,
      anno: 2022,
      caratula: "González c/ Empresa Norte s/ Despido",
      ciudad: "Neuquén",
    },
    {
      id: 6,
      codigo_organismo: "JZAFA",
      tipo: "LEG",
      numero: 33,
      anno: 2023,
      caratula: "Adopción de Pérez",
      ciudad: "Zapala",
    },
    {
      id: 7,
      codigo_organismo: "JJUCI",
      tipo: "EXP",
      numero: 56,
      anno: 2024,
      caratula: "Romero c/ Municipalidad s/ Amparo",
      ciudad: "Junín de los Andes",
    },
    {
      id: 8,
      codigo_organismo: "JNQEJ",
      tipo: "EXP",
      numero: 89,
      anno: 2025,
      caratula: "Cooperativa c/ Díaz s/ Cobro de Pesos",
      ciudad: "Neuquén",
    },
    {
      id: 9,
      codigo_organismo: "JZALA",
      tipo: "EXP",
      numero: 15,
      anno: 2022,
      caratula: "Torres c/ Construcciones Sur s/ Accidente Laboral",
      ciudad: "Zapala",
    },
    {
      id: 10,
      codigo_organismo: "JJUFA",
      tipo: "EXP",
      numero: 7,
      anno: 2025,
      caratula: "Ruiz c/ Ruiz s/ Tenencia",
      ciudad: "Junín de los Andes",
    },
    {
      id: 11,
      codigo_organismo: "JNQCI",
      tipo: "EXP",
      numero: 120,
      anno: 2025,
      caratula: "López c/ García s/ Incumplimiento Contractual",
      ciudad: "Neuquén",
    },
    {
      id: 12,
      codigo_organismo: "JZACI",
      tipo: "LEG",
      numero: 22,
      anno: 2022,
      caratula: "Sucesión de Martínez",
      ciudad: "Zapala",
    },
  ]);
}
